<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /home/jens/PhpstormProjects/baluarte/templates/layout.latte */
final class Template_f83114ea17 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html';
		echo LR\HtmlHelpers::formatAttribute(' lang', $locale ?? 'en') /* pos 2:14 */;
		echo LR\HtmlHelpers::formatDataAttribute(' data-theme', $config['gui']['theme'] ?? 'baluarte') /* pos 2:45 */;
		echo '>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>';
		if ($this->hasBlock('title')) /* pos 6:12 */ {
			$this->renderBlock('title', [], 'html') /* pos 6:25 */;
			echo ' - ';
		}
		echo LR\HtmlHelpers::escapeText('Baluarte') /* pos 6:51 */;
		echo ' Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        dark: \'#08121c\',
                    }
                }
            },
            daisyui: {
                themes: [
                    {
                        baluarte: {
                            "primary": "#3b82f6",
                            "secondary": "#64748b",
                            "accent": "#1fb2a6",
                            "neutral": "#191d24",
                            "base-100": "#08121c",
                            "info": "#3abff8",
                            "success": "#36d399",
                            "warning": "#fbbd23",
                            "error": "#f87272",
                        },
                    },
                    {
                        "baluarte_light": {
                            "primary": "#3b82f6",
                            "secondary": "#64748b",
                            "accent": "#1fb2a6",
                            "neutral": "#f3f4f6",
                            "base-100": "#ffffff",
                            "info": "#3abff8",
                            "success": "#36d399",
                            "warning": "#fbbd23",
                            "error": "#f87272",
                        },
                    },
                ],
            },
        }
    </script>
    <style>
        [data-theme="baluarte"] body { background-color: #08121c; color: #e2e8f0; }
        [data-theme="baluarte_light"] body { background-color: #ffffff; color: #1f2937; }
    </style>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
</head>
<body class="min-h-screen bg-base-100">
    <div class="drawer lg:drawer-open">
        <input id="my-drawer-2" type="checkbox" class="drawer-toggle" />
        <div class="drawer-content flex flex-col">
            <!-- Navbar -->
            <div class="w-full navbar bg-base-200 lg:hidden">
                <div class="flex-none">
                    <label for="my-drawer-2" class="btn btn-square btn-ghost">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="4 6h16M4 12h16M4 18h16"></path></svg>
                    </label>
                </div>
                <div class="flex-1 px-2 mx-2">
                    <img src="assets/img/logo.jpg"';
		echo LR\HtmlHelpers::formatAttribute(' alt', 'Baluarte');
		echo ' class="h-8 w-8 mr-2 rounded">
                    ';
		echo LR\HtmlHelpers::escapeText('Baluarte') /* pos 71:21 */;
		echo '
                </div>
            </div>
            
            <!-- Page content here -->
            <main class="p-6">
';
		$this->renderBlock('content', [], 'html') /* pos 77:17 */;
		echo '            </main>
        </div> 
        <div class="drawer-side">
            <label for="my-drawer-2" aria-label="close sidebar" class="drawer-overlay"></label> 
            <ul class="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
                <!-- Sidebar content here -->
                <li class="mb-4">
                    <div class="flex items-center gap-2 text-xl font-bold">
                        <img src="assets/img/logo.jpg"';
		echo LR\HtmlHelpers::formatAttribute(' alt', 'Baluarte');
		echo ' class="h-10 w-10 rounded">
                        <span>';
		echo LR\HtmlHelpers::escapeText('Baluarte') /* pos 87:31 */;
		echo '</span>
                    </div>
                </li>
                <li><a href="/?page=dashboard" class="';
		if ($page === 'dashboard') /* pos 90:55 */ {
			echo 'active';
		}
		echo '"><i class="bi bi-speedometer2"></i> ';
		echo LR\HtmlHelpers::escapeText('Dashboard') /* pos 90:129 */;
		echo '</a></li>
                <li><a href="/?page=bans" class="';
		if ($page === 'bans') /* pos 91:50 */ {
			echo 'active';
		}
		echo '"><i class="bi bi-shield-slash"></i> ';
		echo LR\HtmlHelpers::escapeText('Active Bans') /* pos 91:119 */;
		echo '</a></li>
                <li><a href="/?page=settings" class="';
		if ($page === 'settings') /* pos 92:54 */ {
			echo 'active';
		}
		echo '"><i class="bi bi-gear"></i> ';
		echo LR\HtmlHelpers::escapeText('Settings') /* pos 92:119 */;
		echo '</a></li>
                <li><a href="/?page=logout" class="text-error"><i class="bi bi-box-arrow-right"></i> ';
		echo LR\HtmlHelpers::escapeText('Logout') /* pos 93:102 */;
		echo '</a></li>
                <li class="mt-auto opacity-50 text-xs flex items-center justify-between">
                    <span>';
		echo LR\HtmlHelpers::escapeText('1.2.0') /* pos 95:27 */;
		echo '</span>
                    <form method="get" class="ml-2">
                        <label class="label text-xs mr-2">';
		echo LR\HtmlHelpers::escapeText('Language') /* pos 97:59 */;
		echo '</label>
                        <select name="lang" class="select select-bordered select-xs" onchange="this.form.submit()">
';
		foreach ($availableLocales as $l) /* pos 99:29 */ {
			echo '                                <option';
			echo LR\HtmlHelpers::formatAttribute(' value', $l) /* pos 100:49 */;
			echo ' ';
			if ($l === ($locale ?? 'en')) /* pos 100:54 */ {
				echo 'selected';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText($l) /* pos 100:97 */;
			echo '</option>
';

		}

		echo '                        </select>
                    </form>
                </li>
            </ul>
        </div>
    </div>
';
		if ($this->hasBlock('scripts')) /* pos 108:5 */ {
			$this->renderBlock('scripts', [], 'html') /* pos 108:20 */;
		}
		echo '</body>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['l' => '99'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
