<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /home/jens/PhpstormProjects/baluarte/public/../templates/settings.latte */
final class Template_63093df6bd extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* pos 5:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['patternId' => '174', 'pattern' => '174'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block title} on line 3 */
	public function blockTitle(array $ʟ_args): void
	{
		echo LR\HtmlHelpers::escapeText('Settings') /* pos 3:14 */;
	}


	/** {block content} on line 5 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		if (isset($_GET['saved'])) /* pos 6:1 */ {
			echo '<div class="alert alert-success shadow-lg mb-6">
    <div>
        <i class="bi bi-check-circle-fill"></i>
        <span>';
			echo LR\HtmlHelpers::escapeText('Settings saved successfully!') /* pos 10:15 */;
			echo '</span>
    </div>
</div>
';
		}
		echo '
<form method="POST">
    <input type="hidden" name="action" value="update_config">

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div class="space-y-6">
            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">';
		echo LR\HtmlHelpers::escapeText('General Settings') /* pos 22:44 */;
		echo '</h2>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('Database Path') /* pos 24:71 */;
		echo '</span></label>
                        <input type="text" name="db_path" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['database']['path'] ?? 'baluarte.sqlite') /* pos 25:103 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('GeoIP Database Path') /* pos 28:71 */;
		echo '</span></label>
                        <input type="text" name="geoip_path" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['geoip']['database_path'] ?? '') /* pos 29:106 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('AbuseIPDB API Key') /* pos 32:71 */;
		echo '</span></label>
                        <input type="password" name="abuseipdb_key" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['api']['abuseipdb']['key'] ?? '') /* pos 33:113 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('API JWT Secret') /* pos 36:71 */;
		echo '</span></label>
                        <input type="text" name="jwt_secret" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['api']['jwt_secret'] ?? '') /* pos 37:106 */;
		echo '>
                        <label class="label"><span class="label-text-alt opacity-70">';
		echo LR\HtmlHelpers::escapeText('Leave empty to disable JWT authentication for API.') /* pos 38:86 */;
		echo '</span></label>
                    </div>
                </div>
            </div>

            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">';
		echo LR\HtmlHelpers::escapeText('Firewall Settings') /* pos 45:44 */;
		echo '</h2>
                    <div class="form-control">
                        <label class="label cursor-pointer justify-start gap-4">
                            <input type="checkbox" name="firewall_enabled" class="checkbox checkbox-primary" ';
		if (isset($config['firewall']['enabled']) && $config['firewall']['enabled']) /* pos 48:110 */ {
			echo 'checked';
		}
		echo '>
                            <span class="label-text">';
		echo LR\HtmlHelpers::escapeText('Enable Firewall Integration') /* pos 49:54 */;
		echo '</span>
                        </label>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('Firewall Driver') /* pos 53:71 */;
		echo '</span></label>
                        <select name="firewall_driver" class="select select-bordered w-full">
                            <option value="ufw" ';
		if (($config['firewall']['driver'] ?? '') === 'ufw') /* pos 55:49 */ {
			echo 'selected';
		}
		echo '>UFW</option>
                            <option value="iptables" ';
		if (($config['firewall']['driver'] ?? '') === 'iptables') /* pos 56:54 */ {
			echo 'selected';
		}
		echo '>iptables</option>
                            <option value="nftables" ';
		if (($config['firewall']['driver'] ?? '') === 'nftables') /* pos 57:54 */ {
			echo 'selected';
		}
		echo '>nftables</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">';
		echo LR\HtmlHelpers::escapeText('Logging Settings') /* pos 65:44 */;
		echo '</h2>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('Max Log Files') /* pos 67:71 */;
		echo '</span></label>
                        <input type="number" name="logging_max_files" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['logging']['max_files'] ?? 7) /* pos 68:115 */;
		echo '>
                    </div>
                </div>
            </div>

            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">';
		echo LR\HtmlHelpers::escapeText('GUI Authentication') /* pos 75:44 */;
		echo '</h2>
                    <input type="hidden" name="action_gui" value="update_gui_settings">
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('New Password') /* pos 78:75 */;
		echo '</span></label>
                            <input type="password" name="new_password" class="input input-bordered w-full" placeholder="Leave empty to keep current">
                            <label class="label"><span class="label-text-alt opacity-70">';
		echo LR\HtmlHelpers::escapeText('Security: Use a strong password.') /* pos 80:90 */;
		echo '</span></label>
                        </div>

                        <div class="form-control w-full">
                            <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('UI Theme') /* pos 84:75 */;
		echo '</span></label>
                            <select name="theme" class="select select-bordered w-full">
                                <option value="baluarte" ';
		if (($config['gui']['theme'] ?? 'baluarte') === 'baluarte') /* pos 86:58 */ {
			echo 'selected';
		}
		echo '>';
		echo LR\HtmlHelpers::escapeText('Dark (Baluarte)') /* pos 86:131 */;
		echo '</option>
                                <option value="baluarte_light" ';
		if (($config['gui']['theme'] ?? '') === 'baluarte_light') /* pos 87:64 */ {
			echo 'selected';
		}
		echo '>';
		echo LR\HtmlHelpers::escapeText('Light (Baluarte)') /* pos 87:135 */;
		echo '</option>
                            </select>
                        </div>

                        <div class="divider">';
		echo LR\HtmlHelpers::escapeText('Two-Factor Authentication') /* pos 91:46 */;
		echo '</div>

                        <div class="form-control">
                            <label class="label cursor-pointer justify-start gap-4">
                                <input type="checkbox" name="two_factor_enabled" class="checkbox checkbox-primary" ';
		if (isset($config['gui']['two_factor_enabled']) && $config['gui']['two_factor_enabled']) /* pos 95:116 */ {
			echo 'checked';
		}
		echo '>
                                <span class="label-text text-lg font-semibold">';
		echo LR\HtmlHelpers::escapeText('Enable 2FA') /* pos 96:80 */;
		echo '</span>
                            </label>
                        </div>

';
		if ($twoFactorSecret) /* pos 100:25 */ {
			echo '                            <div class="mt-4 flex flex-col items-center p-4 bg-gray-100 rounded-lg">
                                <img';
			echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($qrCode)) /* pos 102:44 */;
			echo ' alt="2FA QR Code" class="w-48 h-48">
                                <p class="text-black font-mono mt-2 text-sm">';
			echo LR\HtmlHelpers::escapeText($twoFactorSecret) /* pos 103:78 */;
			echo '</p>
                            </div>
                            <p class="text-xs opacity-70 mt-2">';
			echo LR\HtmlHelpers::escapeText('Scan this QR code with your authenticator app (e.g., Google Authenticator, Authy).') /* pos 105:64 */;
			echo '</p>
';
		}
		echo '
                        <div class="mt-4">
                            <button type="submit" name="regenerate_2fa" class="btn btn-outline btn-sm btn-warning w-full" onclick="return confirm(\'';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs('This will invalidate your current 2FA setup. Are you sure?')) /* pos 109:148 */;
		echo '\')">
                                ';
		if ($twoFactorSecret) /* pos 110:33 */ {
			echo LR\HtmlHelpers::escapeText('Regenerate 2FA Secret') /* pos 110:54 */;
		} else /* pos 110:86 */ {
			echo LR\HtmlHelpers::escapeText('Setup 2FA') /* pos 110:92 */;
		}
		echo '
                            </button>
                        </div>

                        <div class="card-actions mt-6">
                            <button type="submit" name="action" value="update_gui_settings" class="btn btn-primary w-full">';
		echo LR\HtmlHelpers::escapeText('Save GUI Settings') /* pos 115:124 */;
		echo '</button>
                        </div>
                    </div>
            </div>
        </div>

        <div class="space-y-6">
            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">';
		echo LR\HtmlHelpers::escapeText('Notifications (Webhook)') /* pos 124:44 */;
		echo '</h2>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('Webhook URL') /* pos 126:71 */;
		echo '</span></label>
                        <input type="text" name="webhook_url" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['webhook']['url'] ?? '') /* pos 127:107 */;
		echo '>
                    </div>
                </div>
            </div>

            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">';
		echo LR\HtmlHelpers::escapeText('Notifications (MQTT)') /* pos 134:44 */;
		echo '</h2>
                    <div class="form-control">
                        <label class="label cursor-pointer justify-start gap-4">
                            <input type="checkbox" name="mqtt_enabled" class="checkbox checkbox-primary" ';
		if (isset($config['notifications']['mqtt']['enabled']) && $config['notifications']['mqtt']['enabled']) /* pos 137:106 */ {
			echo 'checked';
		}
		echo '>
                            <span class="label-text">';
		echo LR\HtmlHelpers::escapeText('Enable MQTT') /* pos 138:54 */;
		echo '</span>
                        </label>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('MQTT Host') /* pos 142:71 */;
		echo '</span></label>
                        <input type="text" name="mqtt_host" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['host'] ?? 'localhost') /* pos 143:105 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('MQTT Port') /* pos 146:71 */;
		echo '</span></label>
                        <input type="number" name="mqtt_port" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['port'] ?? 1883) /* pos 147:107 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('MQTT Client ID') /* pos 150:71 */;
		echo '</span></label>
                        <input type="text" name="mqtt_client_id" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['client_id'] ?? 'baluarte') /* pos 151:110 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('MQTT Username') /* pos 154:71 */;
		echo '</span></label>
                        <input type="text" name="mqtt_username" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['username'] ?? '') /* pos 155:109 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('MQTT Password') /* pos 158:71 */;
		echo '</span></label>
                        <input type="password" name="mqtt_password" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['password'] ?? '') /* pos 159:113 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">';
		echo LR\HtmlHelpers::escapeText('MQTT Topic Prefix') /* pos 162:71 */;
		echo '</span></label>
                        <input type="text" name="mqtt_topic_prefix" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['topic_prefix'] ?? 'baluarte') /* pos 163:113 */;
		echo '>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card bg-base-200 shadow-xl mt-6">
        <div class="card-body">
            <h2 class="card-title mb-4">';
		echo LR\HtmlHelpers::escapeText('Log Patterns') /* pos 172:41 */;
		echo '</h2>
            <div id="patterns-container" class="space-y-4">
';
		foreach ($config['patterns'] ?? [] as $patternId => $pattern) /* pos 174:17 */ {
			echo '                <div class="p-4 bg-base-300 rounded-lg">
                    <h3 class="font-bold mb-2 text-primary">';
			echo LR\HtmlHelpers::escapeText(($this->filters->translate)('settings.patterns.pattern', $patternId)) /* pos 176:61 */;
			echo '</h3>
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text text-xs">';
			echo LR\HtmlHelpers::escapeText('Regex') /* pos 179:83 */;
			echo '</span></label>
                            <input type="text" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 180:63 */;
			echo '][regex]" class="input input-bordered input-sm w-full font-mono"';
			echo LR\HtmlHelpers::formatAttribute(' value', $pattern['regex']) /* pos 180:148 */;
			echo '>
                        </div>
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text text-xs">';
			echo LR\HtmlHelpers::escapeText('Reason') /* pos 183:83 */;
			echo '</span></label>
                            <input type="text" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 184:63 */;
			echo '][reason]" class="input input-bordered input-sm w-full"';
			echo LR\HtmlHelpers::formatAttribute(' value', $pattern['reason'] ?? '') /* pos 184:139 */;
			echo '>
                        </div>
                        <div class="form-control">
                            <label class="label cursor-pointer justify-start gap-4">
                                <span class="label-text text-xs">';
			echo LR\HtmlHelpers::escapeText('Enabled') /* pos 188:66 */;
			echo '</span>
                                <input type="checkbox" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 189:71 */;
			echo '][enabled]" class="checkbox checkbox-xs" ';
			if ($pattern['enabled']) /* pos 189:124 */ {
				echo 'checked';
			}
			echo '>
                            </label>
                        </div>
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text text-xs">';
			echo LR\HtmlHelpers::escapeText('Format (optional)') /* pos 193:83 */;
			echo '</span></label>
                            <input type="text" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 194:63 */;
			echo '][format]" class="input input-bordered input-sm w-full"';
			echo LR\HtmlHelpers::formatAttribute(' value', $pattern['format'] ?? '') /* pos 194:139 */;
			echo ' placeholder="e.g. json">
                        </div>
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text text-xs">';
			echo LR\HtmlHelpers::escapeText('Field (optional)') /* pos 197:83 */;
			echo '</span></label>
                            <input type="text" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 198:63 */;
			echo '][field]" class="input input-bordered input-sm w-full"';
			echo LR\HtmlHelpers::formatAttribute(' value', $pattern['field'] ?? '') /* pos 198:138 */;
			echo ' placeholder="e.g. log">
                        </div>
                    </div>
                </div>
';

		}

		echo '            </div>

            <div class="divider">';
		echo LR\HtmlHelpers::escapeText('Add New Pattern') /* pos 205:34 */;
		echo '</div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">';
		echo LR\HtmlHelpers::escapeText('ID (e.g. ssh_fail)') /* pos 209:75 */;
		echo '</span></label>
                    <input type="text" name="new_pattern_id" class="input input-bordered input-sm w-full">
                </div>
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">';
		echo LR\HtmlHelpers::escapeText('Regex') /* pos 213:75 */;
		echo '</span></label>
                    <input type="text" name="new_pattern_regex" class="input input-bordered input-sm w-full font-mono">
                </div>
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">';
		echo LR\HtmlHelpers::escapeText('Reason') /* pos 217:75 */;
		echo '</span></label>
                    <input type="text" name="new_pattern_reason" class="input input-bordered input-sm w-full">
                </div>
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">';
		echo LR\HtmlHelpers::escapeText('Format (optional)') /* pos 221:75 */;
		echo '</span></label>
                    <input type="text" name="new_pattern_format" class="input input-bordered input-sm w-full" placeholder="e.g. json">
                </div>
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">';
		echo LR\HtmlHelpers::escapeText('Field (optional)') /* pos 225:75 */;
		echo '</span></label>
                    <input type="text" name="new_pattern_field" class="input input-bordered input-sm w-full" placeholder="e.g. log">
                </div>
            </div>
        </div>
    </div>

            <div class="card-actions justify-end mt-8">
                <button type="submit" class="btn btn-primary">';
		echo LR\HtmlHelpers::escapeText('Save Configuration') /* pos 233:63 */;
		echo '</button>
            </div>
</form>
';
	}
}
