<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /home/jens/PhpstormProjects/baluarte/public/../templates/settings.latte */
final class Template_b2641b2830 extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* pos 5:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['patternId' => '176', 'pattern' => '176'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block title} on line 3 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Settings';
	}


	/** {block content} on line 5 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		if (isset($_GET['saved'])) /* pos 6:1 */ {
			echo '<div class="alert alert-success shadow-lg mb-6">
    <div>
        <i class="bi bi-check-circle-fill"></i>
        <span>Settings saved successfully!</span>
    </div>
</div>
';
		}
		echo '
<form method="POST">
    <input type="hidden" name="action" value="update_config">

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div class="space-y-6">
            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">General Settings</h2>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">Database Path</span></label>
                        <input type="text" name="db_path" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['database']['path'] ?? 'baluarte.sqlite') /* pos 25:103 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">GeoIP Database Path</span></label>
                        <input type="text" name="geoip_path" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['geoip']['database_path'] ?? '') /* pos 29:106 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">AbuseIPDB API Key</span></label>
                        <input type="password" name="abuseipdb_key" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['api']['abuseipdb']['key'] ?? '') /* pos 33:113 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">API JWT Secret</span></label>
                        <input type="text" name="jwt_secret" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['api']['jwt_secret'] ?? '') /* pos 37:106 */;
		echo '>
                        <label class="label"><span class="label-text-alt opacity-70">Leave empty to disable JWT authentication for API.</span></label>
                    </div>
                </div>
            </div>

            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">Firewall Settings</h2>
                    <div class="form-control">
                        <label class="label cursor-pointer justify-start gap-4">
                            <input type="checkbox" name="firewall_enabled" class="checkbox checkbox-primary" ';
		if (isset($config['firewall']['enabled']) && $config['firewall']['enabled']) /* pos 48:110 */ {
			echo 'checked';
		}
		echo '>
                            <span class="label-text">Enable Firewall Integration</span>
                        </label>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">Firewall Driver</span></label>
                        <select name="firewall_driver" class="select select-bordered w-full">
                            <option value="ufw" ';
		if (($config['firewall']['driver'] ?? '') === 'ufw') /* pos 55:49 */ {
			echo 'selected';
		}
		echo '>UFW</option>
                            <option value="iptables" ';
		if (($config['firewall']['driver'] ?? '') === 'iptables') /* pos 56:54 */ {
			echo 'selected';
		}
		echo '>iptables</option>
                            <option value="nftables" ';
		if (($config['firewall']['driver'] ?? '') === 'nftables') /* pos 57:54 */ {
			echo 'selected';
		}
		echo '>nftables</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">Logging Settings</h2>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">Max Log Files</span></label>
                        <input type="number" name="logging_max_files" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['logging']['max_files'] ?? 7) /* pos 68:115 */;
		echo '>
                    </div>
                </div>
            </div>

            <div class="card bg-base-200 shadow-xl">
                <form method="POST">
                    <input type="hidden" name="action" value="update_gui_settings">
                    <div class="card-body">
                        <h2 class="card-title">GUI Authentication</h2>
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text">New Password</span></label>
                            <input type="password" name="new_password" class="input input-bordered w-full" placeholder="Leave empty to keep current">
                            <label class="label"><span class="label-text-alt opacity-70">Security: Use a strong password.</span></label>
                        </div>

                        <div class="form-control w-full">
                            <label class="label"><span class="label-text">UI Theme</span></label>
                            <select name="theme" class="select select-bordered w-full">
                                <option value="baluarte" ';
		if (($config['gui']['theme'] ?? 'baluarte') === 'baluarte') /* pos 87:58 */ {
			echo 'selected';
		}
		echo '>Dark (Baluarte)</option>
                                <option value="baluarte_light" ';
		if (($config['gui']['theme'] ?? '') === 'baluarte_light') /* pos 88:64 */ {
			echo 'selected';
		}
		echo '>Light (Baluarte)</option>
                            </select>
                        </div>

                        <div class="divider">Two-Factor Authentication</div>

                        <div class="form-control">
                            <label class="label cursor-pointer justify-start gap-4">
                                <input type="checkbox" name="two_factor_enabled" class="checkbox checkbox-primary" ';
		if (isset($config['gui']['two_factor_enabled']) && $config['gui']['two_factor_enabled']) /* pos 96:116 */ {
			echo 'checked';
		}
		echo '>
                                <span class="label-text text-lg font-semibold">Enable 2FA</span>
                            </label>
                        </div>

';
		if ($twoFactorSecret) /* pos 101:25 */ {
			echo '                            <div class="mt-4 flex flex-col items-center p-4 bg-gray-100 rounded-lg">
                                <img';
			echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($qrCode)) /* pos 103:44 */;
			echo ' alt="2FA QR Code" class="w-48 h-48">
                                <p class="text-black font-mono mt-2 text-sm">';
			echo LR\HtmlHelpers::escapeText($twoFactorSecret) /* pos 104:78 */;
			echo '</p>
                            </div>
                            <p class="text-xs opacity-70 mt-2">Scan this QR code with your authenticator app (e.g., Google Authenticator, Authy).</p>
';
		}
		echo '
                        <div class="mt-4">
                            <button type="submit" name="regenerate_2fa" class="btn btn-outline btn-sm btn-warning w-full" onclick="return confirm(\'This will invalidate your current 2FA setup. Are you sure?\')">
                                ';
		if ($twoFactorSecret) /* pos 111:33 */ {
			echo 'Regenerate 2FA Secret';
		} else /* pos 111:75 */ {
			echo 'Setup 2FA';
		}
		echo '
                            </button>
                        </div>

                        <div class="card-actions mt-6">
                            <button type="submit" class="btn btn-primary w-full">Save GUI Settings</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="space-y-6">
            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">Notifications (Webhook)</h2>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">Webhook URL</span></label>
                        <input type="text" name="webhook_url" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['webhook']['url'] ?? '') /* pos 129:107 */;
		echo '>
                    </div>
                </div>
            </div>

            <div class="card bg-base-200 shadow-xl">
                <div class="card-body">
                    <h2 class="card-title">Notifications (MQTT)</h2>
                    <div class="form-control">
                        <label class="label cursor-pointer justify-start gap-4">
                            <input type="checkbox" name="mqtt_enabled" class="checkbox checkbox-primary" ';
		if (isset($config['notifications']['mqtt']['enabled']) && $config['notifications']['mqtt']['enabled']) /* pos 139:106 */ {
			echo 'checked';
		}
		echo '>
                            <span class="label-text">Enable MQTT</span>
                        </label>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">MQTT Host</span></label>
                        <input type="text" name="mqtt_host" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['host'] ?? 'localhost') /* pos 145:105 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">MQTT Port</span></label>
                        <input type="number" name="mqtt_port" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['port'] ?? 1883) /* pos 149:107 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">MQTT Client ID</span></label>
                        <input type="text" name="mqtt_client_id" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['client_id'] ?? 'baluarte') /* pos 153:110 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">MQTT Username</span></label>
                        <input type="text" name="mqtt_username" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['username'] ?? '') /* pos 157:109 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">MQTT Password</span></label>
                        <input type="password" name="mqtt_password" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['password'] ?? '') /* pos 161:113 */;
		echo '>
                    </div>
                    <div class="form-control w-full">
                        <label class="label"><span class="label-text">MQTT Topic Prefix</span></label>
                        <input type="text" name="mqtt_topic_prefix" class="input input-bordered w-full"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['notifications']['mqtt']['topic_prefix'] ?? 'baluarte') /* pos 165:113 */;
		echo '>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card bg-base-200 shadow-xl mt-6">
        <div class="card-body">
            <h2 class="card-title mb-4">Log Patterns</h2>
            <div id="patterns-container" class="space-y-4">
';
		foreach ($config['patterns'] ?? [] as $patternId => $pattern) /* pos 176:17 */ {
			echo '                <div class="p-4 bg-base-300 rounded-lg">
                    <h3 class="font-bold mb-2 text-primary">Pattern: ';
			echo LR\HtmlHelpers::escapeText($patternId) /* pos 178:70 */;
			echo '</h3>
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text text-xs">Regex</span></label>
                            <input type="text" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 182:63 */;
			echo '][regex]" class="input input-bordered input-sm w-full font-mono"';
			echo LR\HtmlHelpers::formatAttribute(' value', $pattern['regex']) /* pos 182:148 */;
			echo '>
                        </div>
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text text-xs">Reason</span></label>
                            <input type="text" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 186:63 */;
			echo '][reason]" class="input input-bordered input-sm w-full"';
			echo LR\HtmlHelpers::formatAttribute(' value', $pattern['reason'] ?? '') /* pos 186:139 */;
			echo '>
                        </div>
                        <div class="form-control">
                            <label class="label cursor-pointer justify-start gap-4">
                                <span class="label-text text-xs">Enabled</span>
                                <input type="checkbox" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 191:71 */;
			echo '][enabled]" class="checkbox checkbox-xs" ';
			if ($pattern['enabled']) /* pos 191:124 */ {
				echo 'checked';
			}
			echo '>
                            </label>
                        </div>
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text text-xs">Format (optional)</span></label>
                            <input type="text" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 196:63 */;
			echo '][format]" class="input input-bordered input-sm w-full"';
			echo LR\HtmlHelpers::formatAttribute(' value', $pattern['format'] ?? '') /* pos 196:139 */;
			echo ' placeholder="e.g. json">
                        </div>
                        <div class="form-control w-full">
                            <label class="label"><span class="label-text text-xs">Field (optional)</span></label>
                            <input type="text" name="patterns[';
			echo LR\HtmlHelpers::escapeAttr($patternId) /* pos 200:63 */;
			echo '][field]" class="input input-bordered input-sm w-full"';
			echo LR\HtmlHelpers::formatAttribute(' value', $pattern['field'] ?? '') /* pos 200:138 */;
			echo ' placeholder="e.g. log">
                        </div>
                    </div>
                </div>
';

		}

		echo '            </div>

            <div class="divider">Add New Pattern</div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">ID (e.g. ssh_fail)</span></label>
                    <input type="text" name="new_pattern_id" class="input input-bordered input-sm w-full">
                </div>
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">Regex</span></label>
                    <input type="text" name="new_pattern_regex" class="input input-bordered input-sm w-full font-mono">
                </div>
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">Reason</span></label>
                    <input type="text" name="new_pattern_reason" class="input input-bordered input-sm w-full">
                </div>
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">Format (optional)</span></label>
                    <input type="text" name="new_pattern_format" class="input input-bordered input-sm w-full" placeholder="e.g. json">
                </div>
                <div class="form-control w-full">
                    <label class="label"><span class="label-text text-xs">Field (optional)</span></label>
                    <input type="text" name="new_pattern_field" class="input input-bordered input-sm w-full" placeholder="e.g. log">
                </div>
            </div>
        </div>
    </div>

    <div class="mt-8 mb-12 flex justify-center">
        <button type="submit" class="btn btn-primary btn-lg px-12">Save All Settings</button>
    </div>
</form>
';
	}
}
