<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /home/jens/PhpstormProjects/baluarte/public/../templates/dashboard.latte */
final class Template_2196490d18 extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* pos 5:1 */;
		echo "\n";
		$this->renderBlock('scripts', get_defined_vars()) /* pos 106:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['threatItem' => '59'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block title} on line 3 */
	public function blockTitle(array $ʟ_args): void
	{
		echo LR\HtmlHelpers::escapeText('Dashboard') /* pos 3:14 */;
	}


	/** {block content} on line 5 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
    <div class="stats shadow bg-primary text-primary-content">
        <div class="stat">
            <div class="stat-title text-primary-content opacity-70">';
		echo LR\HtmlHelpers::escapeText('Active Bans') /* pos 9:69 */;
		echo '</div>
            <div class="stat-value">';
		echo LR\HtmlHelpers::escapeText($activeBansCount) /* pos 10:37 */;
		echo '</div>
            <div class="stat-figure text-primary-content">
                <i class="bi bi-shield-slash text-3xl"></i>
            </div>
        </div>
    </div>
    
    <div class="stats shadow bg-warning text-warning-content">
        <div class="stat">
            <div class="stat-title text-warning-content opacity-70">';
		echo LR\HtmlHelpers::escapeText('Threats Detected') /* pos 19:69 */;
		echo '</div>
            <div class="stat-value">';
		echo LR\HtmlHelpers::escapeText($detectedIpsCount) /* pos 20:37 */;
		echo '</div>
            <div class="stat-figure text-warning-content">
                <i class="bi bi-exclamation-triangle text-3xl"></i>
            </div>
        </div>
    </div>
</div>

<div class="card bg-base-200 shadow-xl mb-8">
    <div class="card-body">
        <h2 class="card-title mb-4">';
		echo LR\HtmlHelpers::escapeText('Threat Distribution') /* pos 30:37 */;
		echo '</h2>
        <div id="map" style="height: 400px; width: 100%; border-radius: 1rem;"></div>
    </div>
</div>

<script type="application/json" id="initial-threats">
    ';
		echo LR\HtmlHelpers::convertJSToRawText($detectedIps) /* pos 36:5 */;
		echo '
</script>

<div class="card bg-base-200 shadow-xl">
    <div class="card-body">
        <div class="flex justify-between items-center mb-4">
            <h2 class="card-title">';
		echo LR\HtmlHelpers::escapeText('Recent Threats Detected') /* pos 42:36 */;
		echo '</h2>
            <a href="/blocked-ips" target="_blank" class="btn btn-sm btn-outline">';
		echo LR\HtmlHelpers::escapeText('View Blocklist') /* pos 43:83 */;
		echo '</a>
        </div>
        
        <div class="overflow-x-auto">
            <table class="table table-zebra w-full" id="threats-table">
                <thead>
                    <tr>
                        <th style="display:none">ID</th>
                        <th>';
		echo LR\HtmlHelpers::escapeText('IP Address') /* pos 51:29 */;
		echo '</th>
                        <th>';
		echo LR\HtmlHelpers::escapeText('Country') /* pos 52:29 */;
		echo '</th>
                        <th>';
		echo LR\HtmlHelpers::escapeText('Reason') /* pos 53:29 */;
		echo '</th>
                        <th>';
		echo LR\HtmlHelpers::escapeText('Detected At') /* pos 54:29 */;
		echo '</th>
                        <th>';
		echo LR\HtmlHelpers::escapeText('Actions') /* pos 55:29 */;
		echo '</th>
                    </tr>
                </thead>
                <tbody>
';
		foreach ($detectedIps as $threatItem) /* pos 59:21 */ {
			echo '                    <tr';
			echo LR\HtmlHelpers::formatDataAttribute(' data-id', $threatItem['id']) /* pos 60:35 */;
			echo '>
                        <td style="display:none">';
			echo LR\HtmlHelpers::escapeText($threatItem['id']) /* pos 61:50 */;
			echo '</td>
                        <td>
                            <a href="/?page=ip-details&ip=';
			echo LR\HtmlHelpers::escapeAttr($threatItem['ip']) /* pos 63:59 */;
			echo '" class="hover:underline">
                                <span class="font-mono">';
			echo LR\HtmlHelpers::escapeText($threatItem['ip']) /* pos 64:57 */;
			echo '</span>
                            </a>
                        </td>
                        <td>
';
			if (isset($threatItem['country']) && $threatItem['country'] !== 'Unknown') /* pos 68:29 */ {
				echo '                                <span class="badge badge-ghost">';
				echo LR\HtmlHelpers::escapeText($threatItem['country']) /* pos 69:65 */;
				echo '</span>
';
			} else /* pos 70:29 */ {
				echo '                                <span class="opacity-50">';
				echo LR\HtmlHelpers::escapeText('Unknown') /* pos 71:58 */;
				echo '</span>
';
			}
			echo '                        </td>
                        <td>';
			echo LR\HtmlHelpers::escapeText($threatItem['reason']) /* pos 74:29 */;
			echo '</td>
                        <td><span class="text-xs">';
			echo LR\HtmlHelpers::escapeText($threatItem['detected_at']) /* pos 75:51 */;
			echo '</span></td>
                        <td>
                            <div class="flex gap-2">
                                <a href="/?page=ip-details&ip=';
			echo LR\HtmlHelpers::escapeAttr($threatItem['ip']) /* pos 78:63 */;
			echo '" class="btn btn-xs btn-ghost">
                                    <i class="bi bi-info-circle"></i> ';
			echo LR\HtmlHelpers::escapeText('Details') /* pos 79:71 */;
			echo '
                                </a>
                                <form method="POST">
                                    <input type="hidden" name="action" value="add_ban">
                                    <input type="hidden" name="target"';
			echo LR\HtmlHelpers::formatAttribute(' value', $threatItem['ip']) /* pos 83:80 */;
			echo '>
                                    <input type="hidden" name="type" value="ip">
                                    <button type="submit" class="btn btn-xs btn-error">';
			echo LR\HtmlHelpers::escapeText('Ban IP') /* pos 85:88 */;
			echo '</button>
                                </form>
';
			if (isset($threatItem['country']) && $threatItem['country'] !== 'Unknown') /* pos 87:33 */ {
				echo '                                <form method="POST">
                                    <input type="hidden" name="action" value="add_ban">
                                    <input type="hidden" name="target_country"';
				echo LR\HtmlHelpers::formatAttribute(' value', $threatItem['country']) /* pos 90:88 */;
				echo '>
                                    <input type="hidden" name="type" value="country">
                                    <button type="submit" class="btn btn-xs btn-outline btn-error">';
				echo LR\HtmlHelpers::escapeText('Ban Country') /* pos 92:100 */;
				echo '</button>
                                </form>
';
			}
			echo '                            </div>
                        </td>
                    </tr>
';

		}

		echo '                </tbody>
            </table>
        </div>
    </div>
</div>
';
	}


	/** {block scripts} on line 106 */
	public function blockScripts(array $ʟ_args): void
	{
		echo '<script>
    document.addEventListener(\'DOMContentLoaded\', function() {
        // Map initialization
        const map = L.map(\'map\').setView([20, 0], 2);
        L.tileLayer(\'https://{1}.tile.openstreetmap.org/{2}/{3}/{4}.png\'.replace(\'{1}\',\'s\').replace(\'{2}\',\'z\').replace(\'{3}\',\'x\').replace(\'{4}\',\'y\'), {
            attribution: \'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors\'
        }).addTo(map);

        const markers = {};

        function addMarker(data) {
            if (data.latitude && data.longitude) {
                const markerKey = data.latitude + \',\' + data.longitude;
                if (markers[markerKey]) {
                    markers[markerKey].setPopupContent(markers[markerKey].getPopup().getContent() + \'<br>\' + data.ip + \' (\' + data.reason + \')\');
                } else {
                    markers[markerKey] = L.marker([data.latitude, data.longitude])
                        .addTo(map)
                        .bindPopup(\'<b>\' + (data.city || \'Unknown City\') + \', \' + (data.country || \'Unknown Country\') + \'</b><br>\' + data.ip + \' (\' + data.reason + \')\');
                }
            }
        }

        // Add initial markers
        const initialThreats = JSON.parse(document.getElementById(\'initial-threats\').textContent);
        initialThreats.forEach(addMarker);

        const tableBody = document.querySelector(\'#threats-table tbody\');
        const threatsCount = document.querySelector(\'.stats.bg-warning .stat-value\');
        
        let lastId = 0;
        const firstRow = tableBody.querySelector(\'tr\');
        if (firstRow) {
            lastId = parseInt(firstRow.dataset.id) || 0;
        }

        const evtSource = new EventSource(\'/sse-threats?lastId=\' + lastId);
        
        evtSource.onmessage = function(event) {
            const data = JSON.parse(event.data);
            
            // Add marker to map
            addMarker(data);

            // Check if already in table
            if (document.querySelector(\'tr[data-id="\' + data.id + \'"]\')) return;

            // Create new row
            const row = document.createElement(\'tr\');
            row.dataset.id = data.id;
            row.classList.add(\'animate-pulse\', \'bg-warning\', \'bg-opacity-10\');
            
            const countryBadge = data.country && data.country !== \'Unknown\' 
                ? \'<span class="badge badge-ghost">\' + data.country + \'</span>\' 
                : \'<span class="opacity-50">Unknown</span>\';
            
            const countryBanForm = data.country && data.country !== \'Unknown\'
                ? \'<form method="POST">\' +
                        \'<input type="hidden" name="action" value="add_ban">\' +
                        \'<input type="hidden" name="target_country" value="\' + data.country + \'">\' +
                        \'<input type="hidden" name="type" value="country">\' +
                        \'<button type="submit" class="btn btn-xs btn-outline btn-error">Ban Country</button>\' +
                    \'</form>\'
                : \'\';

            row.innerHTML = \' \\
                <td style="display:none">\' + data.id + \'</td> \\
                <td> \\
                    <a href="/?page=ip-details&ip=\' + data.ip + \'" class="hover:underline"> \\
                        <span class="font-mono">\' + data.ip + \'</span> \\
                    </a> \\
                </td> \\
                <td>\' + countryBadge + \'</td> \\
                <td>\' + data.reason + \'</td> \\
                <td><span class="text-xs">\' + data.detected_at + \'</span></td> \\
                <td> \\
                    <div class="flex gap-2"> \\
                        <a href="/?page=ip-details&ip=\' + data.ip + \'" class="btn btn-xs btn-ghost"> \\
                            <i class="bi bi-info-circle"></i> Details \\
                        </a> \\
                        <form method="POST"> \\
                            <input type="hidden" name="action" value="add_ban"> \\
                            <input type="hidden" name="target" value="\' + data.ip + \'"> \\
                            <input type="hidden" name="type" value="ip"> \\
                            <button type="submit" class="btn btn-xs btn-error">Ban IP</button> \\
                        </form> \\
                        \' + countryBanForm + \' \\
                    </div> \\
                </td>\';
            
            tableBody.insertBefore(row, tableBody.firstChild);
            
            // Update count
            if (threatsCount) {
                threatsCount.textContent = parseInt(threatsCount.textContent) + 1;
            }
            
            // Remove highlight after 5 seconds
            setTimeout(() => {
                row.classList.remove(\'animate-pulse\', \'bg-warning\', \'bg-opacity-10\');
            }, 5000);
            
            // Keep only last 50 rows
            while (tableBody.rows.length > 50) {
                tableBody.deleteRow(tableBody.rows.length - 1);
            }
        };

        evtSource.onerror = function(err) {
            console.error("EventSource failed:", err);
        };
    });
</script>
';
	}
}
