<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: /home/jens/PhpstormProjects/baluarte/public/../templates/bans.latte */
final class Template_dc77bb7111 extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* pos 5:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['banItem' => '22'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block title} on line 3 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Active Bans';
	}


	/** {block content} on line 5 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="card bg-base-200 shadow-xl">
    <div class="card-body">
        <h2 class="card-title mb-4">Active Bans</h2>
        
        <div class="overflow-x-auto">
            <table class="table table-zebra w-full">
                <thead>
                    <tr>
                        <th>Target</th>
                        <th>Type</th>
                        <th>Banned At</th>
                        <th>Expires At</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
';
		foreach ($activeBansDetailed as $banItem) /* pos 22:21 */ {
			echo '                    <tr>
                        <td>
';
			if ($banItem['type'] === 'ip') /* pos 25:29 */ {
				echo '                                <a href="/?page=ip-details&ip=';
				echo LR\HtmlHelpers::escapeAttr($banItem['target']) /* pos 26:63 */;
				echo '" class="hover:underline">
                                    <span class="font-mono">';
				echo LR\HtmlHelpers::escapeText($banItem['target']) /* pos 27:61 */;
				echo '</span>
                                </a>
';
			} else /* pos 29:29 */ {
				echo '                                <span class="font-mono">';
				echo LR\HtmlHelpers::escapeText($banItem['target']) /* pos 30:57 */;
				echo '</span>
';
			}
			echo '                        </td>
                        <td><span class="badge badge-secondary">';
			echo LR\HtmlHelpers::escapeText($banItem['type']) /* pos 33:65 */;
			echo '</span></td>
                        <td><span class="text-xs">';
			echo LR\HtmlHelpers::escapeText($banItem['banned_at']) /* pos 34:51 */;
			echo '</span></td>
                        <td><span class="text-xs">';
			echo LR\HtmlHelpers::escapeText($banItem['expires_at']) /* pos 35:51 */;
			echo '</span></td>
                        <td>
                            <div class="flex gap-2">
';
			if ($banItem['type'] === 'ip') /* pos 38:33 */ {
				echo '                                <a href="/?page=ip-details&ip=';
				echo LR\HtmlHelpers::escapeAttr($banItem['target']) /* pos 39:63 */;
				echo '" class="btn btn-xs btn-ghost">
                                    <i class="bi bi-info-circle"></i> Details
                                </a>
';
			}
			echo '                                <form method="POST">
                                    <input type="hidden" name="action" value="remove_ban">
                                    <input type="hidden" name="ip"';
			echo LR\HtmlHelpers::formatAttribute(' value', $banItem['target']) /* pos 45:76 */;
			echo '>
                                    <button type="submit" class="btn btn-xs btn-outline btn-success">Unban</button>
                                </form>
                            </div>
                        </td>
                    </tr>
';

		}

		echo '                </tbody>
            </table>
        </div>
    </div>
</div>
';
	}
}
